#!/bin/bash

protected_branches=('main' 'master')  # Array of protected branch names
current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

protected=false

# Check if the current branch matches any protected branches
for branch in "${protected_branches[@]}"; do
    if [ "$branch" = "$current_branch" ]; then
        protected=true
        break
    fi
done

if [ "$protected" = true ]; then
    read -p "You're about to push $current_branch, is that what you intended? [y|n] " -n 1 -r < /dev/tty
    echo
    if echo "$REPLY" | grep -E '^[Yy]$' > /dev/null; then
        exit 0 # push will execute
    fi
    exit 1 # push will not execute
else
    exit 0 # push will execute
fi
